### ISSUE TITLE
Realm with RxJava code snippets not up to date.

### ISSUE THREAD

**Issue by kboyarshinov** [GavinThePacMan/daysuntil#1]
Hi @GavinThePacMan.

I see you've used `RealmObservable` and `OnSubscribeRealm` classes from my realm with rxjava repo. I've noticed that you pulled not the latest code, which was actually in development stage (update to latest Realm version). This is my mistake though, I should have not pushed these changes to master branch. Right now `OnSubscribeRealm` changed a while and I'm working on new features and test various usage scenarios. Please take a look to corresponding issue https://github.com/kboyarshinov/realm-rxjava-example/issues/1.

Thanks

**Comment by GavinPacini** [comment]
Hey @kboyarshinov 

Many thanks for letting me know about this! I have updated the code as can be seen in the above commit. Really appreciate your example on GitHub! 

Also, a bit off topic, I saw you had a pull request for deleting an object from Realm. I actually also added a similar method. The reason for this was because upon doing so, I display an undo which allows the user to re-add an event they have removed. 

I achieved this by passing back an `Event` object containing the same information as the `RealmEvent` object in my new `remove` method. This of course means that my `remove` method must return a generic which does not extend from RealmObject. I just wanted to let you know about this in case it was something you wanted to implement! If you don't, I completely understand. It may be a bit unique to my needs!

Either way, thanks again for your example on GitHub! :)

**Comment by kboyarshinov** [comment]
> The reason for this was because upon doing so, I display an undo which allows the user to re-add an event they have removed.

Nice use case :+1:. But as you stated its unique for your needs. Anyway it's an example, not a library. Implement anything you wish upon it.
